sonar.projectKey=turnpiece_TempHist
sonar.organization=turnpiece

sonar.sources=src,server.js,server-local.js
sonar.tests=test
sonar.test.inclusions=test/**/*.{test,spec}.{ts,js}

sonar.exclusions=dist/**,coverage/**,node_modules/**,public/**,**/*.min.js,vite.config.*,vitest.config.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
