name: Update TempHist Cache

on:
  schedule:
    # Run fetch-daily-data every hour
    - cron: "0 * * * *"
    # Run fetch-locations daily at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Update locations (daily only)
        if: github.event.schedule == '0 0 * * *'
        run: node scripts/fetch-locations.js
        env:
          VITE_API_BASE: https://temphist-api-develop.up.railway.app
          API_TOKEN: ${{ secrets.API_TOKEN }}
          OUTPUT_DIR: ./public/data

      - name: Update daily data (hourly)
        if: github.event.schedule == '0 * * * *'
        run: node scripts/fetch-daily-data.js
        env:
          VITE_API_BASE: https://temphist-api-develop.up.railway.app
          API_TOKEN: ${{ secrets.API_TOKEN }}
          OUTPUT_DIR: ./public/data

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet public/data/; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/data/
          git commit -m "Update cache data [skip ci]"
          git push

      - name: No changes detected
        if: steps.check-changes.outputs.changed == 'false'
        run: echo "No data changes detected, skipping commit"
